"""unique_user_id

Revision ID: 18b5805a011b
Revises: 5e1841a28c4b
Create Date: 2025-04-02 19:06:06.721290

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18b5805a011b"
down_revision: str | None = "5e1841a28c4b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "memoryoperationtracker", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "memoryoperationtracker", type_="unique")  # type: ignore
    # ### end Alembic commands ###
