"""add source documents

Revision ID: 8c81a491f69a
Revises: e8f85ea5a3ff
Create Date: 2025-02-07 16:13:29.930586

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "8c81a491f69a"
down_revision: Union[str, None] = "e8f85ea5a3ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentexcerpt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("content", AutoString(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content_md5", AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source_document_id", "chunk_index", "is_active"),
    )
    op.create_index(op.f("ix_documentexcerpt_id"), "documentexcerpt", ["id"], unique=False)
    op.create_table(
        "sourcedocument",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address", AutoString(), nullable=False),
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("content", AutoString(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=False),
        sa.Column("extraction_error", AutoString(), nullable=True),
        sa.Column("content_md5", AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "address"),
    )
    op.create_index(op.f("ix_sourcedocument_id"), "sourcedocument", ["id"], unique=False)
    op.drop_column("contextmessageset", "message_ids_bkp")
    op.drop_column("goal", "embedding_text_md5")
    op.drop_column("goal", "status_updates_bkp")
    op.drop_column("goal", "embedding")
    op.drop_column("memory", "embedding_text_md5")
    op.drop_column("memory", "embedding")
    op.drop_column("message", "tool_calls_bkp")
    op.drop_column("message", "memory_metadata_bkp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("memory_metadata_bkp", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column("message", sa.Column("tool_calls_bkp", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column("memory", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column("memory", sa.Column("embedding_text_md5", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("goal", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column(
        "goal",
        sa.Column(
            "status_updates_bkp",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("goal", sa.Column("embedding_text_md5", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "contextmessageset", sa.Column("message_ids_bkp", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_sourcedocument_id"), table_name="sourcedocument")
    op.drop_table("sourcedocument")
    op.drop_index(op.f("ix_documentexcerpt_id"), table_name="documentexcerpt")
    op.drop_table("documentexcerpt")
    # ### end Alembic commands ###
