services:
  elroy:
    container_name: elroy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    stdin_open: true
    tty: true
    entrypoint: ["elroy"]
    command: []


  elroy-dev:
    container_name: elroy-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    stdin_open: true
    tty: true
    # Uncomment these 2 lines to add docker socket support to run nested dockers
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock
