services:
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: elroy_postgres_test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=elroy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=elroy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elroy"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: 
      - "postgres"
      - "-c"
      - "shared_preload_libraries=vector"

  # alembic:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: alembic
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=postgresql://elroy:password@postgres:5432/elroy
  #     - POSTGRES_USER=elroy
  #     - DOCKER_LOCAL=1
  #   volumes:
  #     - .:/app
  #   command: ["alembic", "upgrade", "head"]

volumes:
  postgres-data: {}
