services:
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: elroy_postgres_test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=elroy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=elroy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elroy"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: 
      - "postgres"
      - "-c"
      - "shared_preload_libraries=vector"

volumes:
  postgres-data: {}
