FROM python:3.11.7-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    python3-dev \
    build-essential \
    git \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy the local repository into the container
COPY . /app/

RUN pip install poetry-core

# Install the local version of elroy
RUN pip install -e . --no-cache-dir

ENV ELROY_HOME=/app/data

RUN mkdir -p /app/data && \
    chmod -R 777 /app/data

# Set the PYTHONPATH
ENV PYTHONPATH=/app
