FROM lunamidori5/pixelarch:quartz

RUN sudo sed -i 's/Quartz/Elroy/g' /etc/os-release

ARG USERNAME=midori-ai

USER $USERNAME
WORKDIR /home/$USERNAME/app

RUN yay -Syu --noconfirm uv && yay -Yccc --noconfirm

COPY . .
ENV ELROY_HOME=/home/$USERNAME/app/data

RUN sudo mkdir -p /home/$USERNAME/app/data
RUN sudo chmod -R 777 /home/$USERNAME/app

ENTRYPOINT ["uv", "run", "elroy"]
CMD ["chat"]
