"""rm json columns

Revision ID: 892ce7b9a77b
Revises: 140daba72332
Create Date: 2024-12-18 08:18:00.389996

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "892ce7b9a77b"
down_revision: Union[str, None] = "140daba72332"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contextmessageset", "message_ids", existing_type=postgresql.JSON(astext_type=sa.Text()), type_=sa.Text(), existing_nullable=True
    )
    op.alter_column(
        "goal",
        "status_updates",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.Text(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_column("goal", "embedding")
    op.drop_column("goal", "embedding_text_md5")
    op.drop_column("memory", "embedding")
    op.drop_column("memory", "embedding_text_md5")
    op.alter_column("message", "tool_calls", existing_type=postgresql.JSON(astext_type=sa.Text()), type_=sa.Text(), existing_nullable=True)
    op.alter_column(
        "message", "memory_metadata", existing_type=postgresql.JSON(astext_type=sa.Text()), type_=sa.Text(), existing_nullable=True
    )
    op.alter_column("vectorstorage", "embedding_data", existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("vectorstorage", "embedding_data", existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False)
    op.alter_column(
        "message", "memory_metadata", existing_type=sa.Text(), type_=postgresql.JSON(astext_type=sa.Text()), existing_nullable=True
    )
    op.alter_column("message", "tool_calls", existing_type=sa.Text(), type_=postgresql.JSON(astext_type=sa.Text()), existing_nullable=True)
    op.add_column("memory", sa.Column("embedding_text_md5", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("memory", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column("goal", sa.Column("embedding_text_md5", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("goal", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.alter_column(
        "goal",
        "status_updates",
        existing_type=sa.Text(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "contextmessageset", "message_ids", existing_type=sa.Text(), type_=postgresql.JSON(astext_type=sa.Text()), existing_nullable=True
    )
        # ### end Alembic commands ###
