"""add archival mem name

Revision ID: 0c3bf53c898a
Revises: 9b8ff0056f91
Create Date: 2024-10-05 11:03:12.983854

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c3bf53c898a"
down_revision: Union[str, None] = "9b8ff0056f91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archivalmemory", sa.Column("name", AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archivalmemory", "name")
    # ### end Alembic commands ###
