"""add metadata

Revision ID: 9b8ff0056f91
Revises: 45223a2c0c67
Create Date: 2024-08-22 19:02:25.837340

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b8ff0056f91"
down_revision: Union[str, None] = "45223a2c0c67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_smswebhooklog_id", table_name="smswebhooklog")
    op.drop_table("smswebhooklog")
    op.add_column("message", sa.Column("memory_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "memory_metadata")
    op.create_table(
        "smswebhooklog",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("info", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="smswebhooklog_pkey"),
    )
    op.create_index("ix_smswebhooklog_id", "smswebhooklog", ["id"], unique=False)
    # ### end Alembic commands ###
