"""add source documents

Revision ID: 202741ec6307
Revises: f880962b9187
Create Date: 2025-02-07 16:13:09.092773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "202741ec6307"
down_revision: Union[str, None] = "f880962b9187"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentexcerpt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("content", AutoString(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content_md5", AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source_document_id", "chunk_index", "is_active"),
    )
    op.create_index(op.f("ix_documentexcerpt_id"), "documentexcerpt", ["id"], unique=False)
    op.create_table(
        "sourcedocument",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address", AutoString(), nullable=False),
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("content", AutoString(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=False),
        sa.Column("extraction_error", AutoString(), nullable=True),
        sa.Column("content_md5", AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "address"),
    )
    op.create_index(op.f("ix_sourcedocument_id"), "sourcedocument", ["id"], unique=False)
    op.drop_table("vectorstorage_metadatachunks00")
    op.drop_table("vectorstorage_metadatachunks02")
    op.drop_table("vectorstorage_metadatatext02")
    op.drop_table("vectorstorage_info")
    op.drop_table("vectorstorage_metadatachunks01")
    op.drop_table("vectorstorage_metadatatext00")
    op.drop_table("vectorstorage_rowids")
    op.drop_table("vectorstorage_vector_chunks00")
    op.drop_table("vectorstorage_chunks")
    op.alter_column("vectorstorage", "source_type", existing_type=sa.NullType(), nullable=False)
    op.alter_column("vectorstorage", "source_id", existing_type=sa.NullType(), nullable=False)
    op.alter_column("vectorstorage", "embedding_data", existing_type=sa.NullType(), nullable=False)
    op.alter_column("vectorstorage", "embedding_text_md5", existing_type=sa.NullType(), nullable=False)
    op.drop_index("sqlite_butoindex_x_1", table_name="vectorstorage")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("sqlite_butoindex_x_1", "vectorstorage", [], unique=1)
    op.alter_column("vectorstorage", "embedding_text_md5", existing_type=sa.NullType(), nullable=True)
    op.alter_column("vectorstorage", "embedding_data", existing_type=sa.NullType(), nullable=True)
    op.alter_column("vectorstorage", "source_id", existing_type=sa.NullType(), nullable=True)
    op.alter_column("vectorstorage", "source_type", existing_type=sa.NullType(), nullable=True)
    op.create_table(
        "vectorstorage_chunks",
        sa.Column("chunk_id", sa.INTEGER(), nullable=True),
        sa.Column("size", sa.INTEGER(), nullable=False),
        sa.Column("validity", sa.BLOB(), nullable=False),
        sa.Column("rowids", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_table(
        "vectorstorage_vector_chunks00",
        sa.Column("rowid", sa.NullType(), nullable=True),
        sa.Column("vectors", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "vectorstorage_rowids",
        sa.Column("rowid", sa.INTEGER(), nullable=True),
        sa.Column("id", sa.NullType(), nullable=True),
        sa.Column("chunk_id", sa.INTEGER(), nullable=True),
        sa.Column("chunk_offset", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "vectorstorage_metadatatext00",
        sa.Column("rowid", sa.NullType(), nullable=True),
        sa.Column("data", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "vectorstorage_metadatachunks01",
        sa.Column("rowid", sa.NullType(), nullable=True),
        sa.Column("data", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "vectorstorage_info",
        sa.Column("key", sa.TEXT(), nullable=True),
        sa.Column("value", sa.NUMERIC(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "vectorstorage_metadatatext02",
        sa.Column("rowid", sa.NullType(), nullable=True),
        sa.Column("data", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "vectorstorage_metadatachunks02",
        sa.Column("rowid", sa.NullType(), nullable=True),
        sa.Column("data", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "vectorstorage_metadatachunks00",
        sa.Column("rowid", sa.NullType(), nullable=True),
        sa.Column("data", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.drop_index(op.f("ix_sourcedocument_id"), table_name="sourcedocument")
    op.drop_table("sourcedocument")
    op.drop_index(op.f("ix_documentexcerpt_id"), table_name="documentexcerpt")
    op.drop_table("documentexcerpt")
    # ### end Alembic commands ###
