"""add background ingestion config

Revision ID: add_background_ingestion_config
Revises: 1c74c74a43e2
Create Date: 2025-08-25 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "add_background_ingestion_config"
down_revision: Union[str, None] = "1c74c74a43e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backgroundingestionconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("watch_directory", AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("recursive", sa.Boolean(), nullable=False),
        sa.Column("include_patterns", AutoString(), nullable=False),
        sa.Column("exclude_patterns", AutoString(), nullable=False),
        sa.Column("last_full_scan", sa.DateTime(), nullable=True),
        sa.Column("last_scan_status", AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backgroundingestionconfig")
    # ### end Alembic commands ###
