services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    environment:
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Redis connection is handled in litellm_config.yaml
    depends_on:
      - redis
    command: ["--config", "/app/config.yaml"]
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    restart: unless-stopped

  # Base configuration for benchmark services
  benchmark:
    build:
      context: ../../..
      dockerfile: Dockerfile
    environment:
      # - AZURE_API_KEY=${AZURE_API_KEY}
      # - AZURE_API_BASE=${AZURE_API_BASE}
      # - AZURE_API_VERSION=${AZURE_API_VERSION}
      - PHOENIX_CLIENT_HEADERS=${PHOENIX_CLIENT_HEADERS}
      - PHOENIX_COLLECTOR_ENDPOINT=${PHOENIX_COLLECTOR_ENDPOINT}
      - OTEL_EXPORTER_OLTP_HEADERS=${OTEL_EXPORTER_OLTP_HEADERS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELROY_CHAT_MODEL=gpt-4o-mini
      - ELROY_EMBEDDING_MODEL=text-embedding-3-small
      - OPENAI_API_KEY=sk-123
      - ELROY_ENABLE_TRACING=1
      - ELROY_LOG_LEVEL=WARN
      - ELROY_TRACING_APP_NAME=elroy-benchmark
      - ELROY_BENCHMARK_DATABASE_URL=postgresql://benchmarking:password@postgres:5432/benchmarking
      - ELROY_DATABASE_URL=postgresql://benchmarking:password@postgres:5432/benchmarking
      - ELROY_CHAT_MODEL_API_BASE=http://litellm:4000
      - ELROY_EMBEDDING_MODEL_API_BASE=http://litellm:4000
      - OPENAI_API_BASE=https://litellm:4000
    volumes:
      - ./data:/app/scripts/benchmarking/longmemeval/data
      - ./:/app/scripts/benchmarking/longmemeval
    depends_on:
      - postgres
      - litellm

    entrypoint: ["python", "/app/scripts/benchmarking/longmemeval/run.py", "/app/scripts/benchmarking/longmemeval/data/longmemeval_s.json"]

  postgres:
    image: ankane/pgvector:v0.5.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=benchmarking
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=benchmarking
    volumes:
      - benchmarking_postgres-data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=vector
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  benchmarking_postgres-data:
