model_list:

- model_name: azure/text-embedding-3-small
  litellm_params:
    model: azure/text-embedding-3-small
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: os.environ/AZURE_API_BASE
- model_name: azure/gpt-4o-turbo
  litellm_params:
    model: azure/gpt-4o-mini
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: os.environ/AZURE_API_BASE

litellm_settings:
  # Optional - Redis Settings
  host: "localhost"  # The host address for the Redis cache. Required if type is "redis".
  port: 6379  # The port number for the Redis cache. Required if type is "redis".
  password: "password"  # The password for the Redis cache. Required if type is "redis".
  namespace: "litellm.caching.caching" # namespace for redis cache
  disable_master_key_return: boolean


# docker run \
#     -v $(pwd)/litellm_config.yaml:/app/config.yaml \
#     -e AZURE_API_KEY=$AZURE_API_KEY \
#     -e AZURE_API_BASE=$AZURE_API_BASE \
#     -e AZURE_API_VERSION=$AZURE_API_VERSION \
#     -p 4000:4000 \
#     ghcr.io/berriai/litellm:main-latest \
#     --config /app/config.yaml --detailed_debug
